### ISSUE TITLE
Possibilty of dynamicly select the database to query

### ISSUE THREAD

**Issue by alexjp** [livehelpnow/tds_ecto#13]
I am in the need of selecting the database in a mssql instance dynamicly. The databases have all the same schema.

Is it possible to specify the database in the query ?

Thanks !

**Comment by mobileoverlord** [comment]
Someone was asking me about this before too. I haven't been able to fully tests this. But I did add support for you to use . in the schema table name. here:
https://github.com/livehelpnow/tds_ecto/blob/master/lib/tds_ecto/connection.ex#L607-L612

I brought this up to others about supporting cross database joins and dynamic queries, but it seems like this is a MSSQL specific thing. Also, you might have to connect to the database `master` instead of a specific db.

**Comment by mobileoverlord** [comment]
Here is the other issue that was referring to specifying the view.
https://github.com/livehelpnow/tds_ecto/issues/4

**Comment by mobileoverlord** [comment]
Im not sure this is going to be officially supported, but I'd like to know if the work around worked
