### ISSUE TITLE
Ecto 3 Support

### ISSUE THREAD

**Issue by collegeimprovements** [livehelpnow/tds_ecto#69]
Does tds/tds_ecto support Ecto 3.x ? 
What would be the value of adapter when we use it with Ecto 3.x ?
`Tds.Ecto` was giving us an compile time error :|

**Comment by mjaric** [comment]
We are moving Tds.Ecto to ecto_sql and should be released with 3.1 if we manage to complete necessary changes

**Comment by collegeimprovements** [comment]
Thanks a lot :)

**Comment by garretttaco** [comment]
Is there a link to the progress of moving tds_ecto into ecto_sql? Any timeframe of when 3.1 may be released?

**Comment by mjaric** [comment]
at the moment, it is in this [fork](https://github.com/mjaric/ecto_sql/tree/tds-support) 

We don't have any timeline set for the release.

**Comment by garretttaco** [comment]
Ok, thank you for linking to the fork and for your work on this project!

**Comment by mtrudel** [comment]
If I understand the current state of affairs, it's not possible to use this library via Ecto 3 except via the fork referenced above. Is that correct? Is there a planned timeline for that?

**Comment by mjaric** [comment]
Yes, and that fork is still work in progress. I think datetime2 is not resolved yet. The rest should be fine. I haven't had time to work on that last 3 months, and I'm working on several projects in parallel so I can't promise anything at the moment.

**Comment by mtrudel** [comment]
I actually had to workaround some `DateTime` strangeness in 1.1 recently, so my head is somewhat in that space at the moment. Is there a specific outline of the work needed that I could take on? Happy to help.

**Comment by mjaric** [comment]
Starting from ecto 3 it uses elixir DateTime, NaiveDateTime for :naive_datetime, :datetime and :datetime2 schema types. Problem is that TDS repository is still using erlang datetime tuple, but if we change that to elixir types then in case of `datetime2` we will lost precision.  In many cases that shouldn't be a problem, but lets say you want to schedule some task for 31th December 2019 23:59:59.9999999 (this is MSSSQL 7 digits precision datetime) if you read that value in elixir, since DateTime is 6 digits precise it what you are going to do, to round it or just flat it?

The rest of the work is to talk with Jose (probably) and update schemas in ecto repo integration_tests folder so they do not use `text` and `ntext` fields since attributes of such type are often used in test with `like` and that does not work in MSSSQL . Further more, some test cases are trying to work with strings over attributes that are of varbinary (ecto binary) type. That also do not work pretty in MSSQL and often throws an error in sql server.

That is so far I know that is not working. Time type is not something I ever used but I know that there was some complains in ecto 2. IT is worth to check it.

**Comment by collegeimprovements** [comment]
@mjaric Thanks a lot for your continuous work on it.
Would it be possible to release this package with known caveats on hex.pm ? 


Hi Community,
I'm connecting, `postgres` and `oracle` in my project and both of them(`postgrex`, `jamdb_oracle`) are using `ecto_sql` and `ecto-3`. Since, `tds` is depending on `ecto-2`, is there any way of using `mssql` with current setup without downgrading whole project to `ecto-2`! 
Any hack, trick or suggestion is highly appreciated.
